version: '3'
services:
  app:
    build: .
    ports:
      - 80:3000
    depends_on:
      - database
  database:
    image: mongo:jammy
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./.volumes/mongodb:/data/db
